### ISSUE TITLE
Receiving notifications from myopenhab which are not created by my account.

### ISSUE THREAD

**Issue by JueBag** [openhab/openhab-cloud#184]
Received a notification on a registered device which is not coming from my openhab instance.
Several other users reported the same in the forum

[https://community.openhab.org/t/is-myopenhab-org-down-i-get-timeout-on-android-and-504-i-think-is-504-on-web-interface/43763/15](url)
[https://community.openhab.org/t/receiving-notifications-via-openhab-cloud-not-originating-from-my-installation/43772/9](url)

**Comment by digitaldan** [comment]
Thanks for the report, we are looking at this now.

**Comment by digitaldan** [comment]
@FlorianSW I think this may have started around the time the registration code was refactored.  Can you take a look as well on this issue.  For the record, we are seeing many, many entries in the userdevices collection that share the same "androidRegistration" or "iosDeviceToken"   as another entry in the collection, so this field is not unique per entry as it should be.  I'm not sure how this is happening.   We can definitely put in a check to make sure this does not happen, but I would still like to know how its happening.

**Comment by FlorianSW** [comment]
Looking into this now. Can you provide an anonymized set of data of the model (like one or two sets of data with the same registration ID)? The deviceId, deviceModel and the deviceType would be interesting :)

**Comment by digitaldan** [comment]
Yes i can do that, I'll ping you privately with some sample data that has been sanitized.  I'll try and find those log entires, the logging has been super verbose which i need to turn down as it makes finding these messages difficult.

**Comment by digitaldan** [comment]
@FlorianSW can you ping me via email? dan@digitaldan.com

**Comment by digitaldan** [comment]
@FlorianSW I don't think the issue is what i originally thought, while there are lots of duplicate push token id's in the system, they seem to be either due to people creating a second (or third) account, or a device changing its id, but still have the same push token id.  There was a ton of data, so it was slow going to do the forensics. That being said, I'm starting to think this may be a load issue and how the websockets are being managed, I'm going to start looking if there's a chance that when a message comes in from a websocket if we could be mistaking its origin for another user when under extreme load (maybe a mongo issue, or redis cache issue?).    We heard from a chorus of users right when we had a server crash on us and all load went to the other one.

**Comment by FlorianSW** [comment]
@digitaldan Thanks for the update! Sounds reasonable, I looked at the code for registering a new android device and I couldn't find any codepath in which it would be possible, that a second device is registered unintentionally to the false person, so I also think, that the problem might be related to the sending code, I'll take a look into that (that's also the part where more changes were made in the recent versions I think).

**Comment by FlorianSW** [comment]
@digitaldan From looking at the code and at the diffs of the respective code lines for sending a notification to a users device(s), I found that I missed some returns in some guard statements (see the PR #188). However, I don't think, that this could result in notifications mistakenly being sent to false users. However, it's something that could be related to this issue and should be fixed anyway.

So far, I wasn't able to reproduce this behaviour :(

**Comment by digitaldan** [comment]
Thanks for the PR!  I was looking at that part as well and noticed the missing return statement, not sure if that could had anything  to do with this, but I try and deploy those changes today to be safe.

**Comment by openhab-5iver** [comment]
My wife is getting notifications on her phone that are not initiated from our system, and do not show in the History. They appear to be coming from the same source, as they have the same content. She is still receiving the notifications that originate from our system. I am not getting the notifications from the mystery source. The issue started about a week ago on 2.3.0 snapshot 1268, and still occurs with 1272. My wife's phone had died a few months back, so we had removed the old one and added another one to her account.

Let me know if there is some info I can provide that would help in troubleshooting this.

**Comment by digitaldan** [comment]
Can you send me the email address you used to register for the cloud service?  support@myopenhab.org

**Comment by FlorianSW** [comment]
@digitaldan Did dyou deployed the changes from PR #188 already (just to make sure, if this can't be the problem anymore)?

Just for some more background infromation (as the code of the notification sending part of openHAB seems to haven't changed in the last time): Can you give a little overview of how openHAB-cloud is currently setup from infrastructure point of view behind myopenhab.org? Especially the number of different instances of the app, as well as the load-balancing software and configuration, would be very interesting :)

I've nothing special in mind, and anything that comes into my mind that could result in such a problem is prevented in the code already :(

@openhab-5iver One question, though: Did your wife miss any notification which you got on your phone? Or did she only get _additional_ messages?

**Comment by openhab-5iver** [comment]
> Can you send me the email address you used to register for the cloud service?

Sent

> One question, though: Did your wife miss any notification which you got on your phone? Or did she only get additional messages?

The service has been a bit unstable lately, so I think we both have missed some, but she has received all of them that I have. The mystery notifications are additional.

**Comment by FlorianSW** [comment]
> for some reason there were two device entries with the same GCM id
Oha, that shouldn't be possible :) I'll open a separate issue (see #195) for that, so that we can at least prevent this in the future with an error, instead of getting corrupted data into our database. However, as this one was the only duplicate entry, this is probably not the root cause of the problem :/

**Comment by openhab-5iver** [comment]
> I have delete both from our DB, if you open the openHAB app fomr the phone again it will register a new ID.

I'll report back if she gets any more mystery notifications. Thank you both for your support!

**Comment by digitaldan** [comment]
@FlorianSW I think it is the root problem, or at least the main one. I have not been communicating well across the various projects here, my apologies.  When we had the initial problem, I found many duplicate entries, sometimes more then two per GCM and APN ID.  There was a correlation between the the registration time on those entries and when we were having server issues that caused both app servers to be rebooted.  I went ahead and delete those registrations 2 weeks ago.  The issue that @openhab-5iver had was the only duplicate in the system as of today, so its still happening, but obviously not as frequent.

I deployed your fix a few days ago, but just yesterday reloaded the app processes to correlate with some Linode server patching, I'm trying to limit restarting  them as it interrupts thousands of connected OH systems.  

You asked about how the systems are setup, we currently have a nginx server which load balances connections to one of 8 node prrocesses running on 2 other servers.  Each server runs 2 processes which are resposnible for the web-sockets from OH instances, and also web requests which need to be proxied back to the OH instance.  The other two processes on the box handle all other web requests, including GCM and APN registrations.  

The balancing of the websockets across multiple servers was introduced  in January ( #137 ), while the general web request load balancing has been there since the beginning of the project.

**Comment by ozzeruk** [comment]
Hello, just to let you know this has started happening on my OpenHab app too as of today. I keep getting weird messages in German. A bit unsettling as it makes me wonder if the installation has been compromised at all. Hope it's a simple fix.

**Comment by digitaldan** [comment]
Hi @ozzeruk I have deleted you android registration, launching the app again will create a new one.  Fortunately there’s no change of a compromised account, the bug is related to duplicate push notification ids , so in very rare cases a message is pushed to two devices instead of one.  But that does not make it any less scary when it happens!

**Comment by ozzeruk** [comment]
Thanks Dan - I'm back up and running again, all good!

**Comment by digitaldan** [comment]
I will leave this open until I confirm this fixes the issue

**Comment by JueBag** [comment]
Some false notifications were reported today, see:
https://community.openhab.org/t/receiving-notifications-via-openhab-cloud-not-originating-from-my-installation/43772/24

Are they related?
