### ISSUE TITLE
Event Log shows only first page

### ISSUE THREAD

**Issue by niggli** [openhab/openhab-cloud#222]
Below the list of events, there are links to further pages of older events. If I click on one of the numbers, all that happens is that the page reloads.

**Comment by cweitkamp** [comment]
I can verify that. The URL changes from e.g. https://myopenhab.org/events to https://myopenhab.org/events?page=1 but the listed entries are still the same. The buttons "Prev" and "Next" do not change anything.

**Comment by cweitkamp** [comment]
@digitaldan I did some research and tried to figure out how I can help: In #174 the usage of page parameters has been fixed. This fix has been overwritten by #194. Can we somehow revert the changes of the `routes/*.js` files? Thanks.

**Comment by Landstad** [comment]
Any news on this?

**Comment by maniac103** [comment]
@cweitkamp Nice find ... I was wondering why the Android app doesn't display all notifications anymore :-/
@marziman This looks like a merge fail in your PR #194...can you please fix that?

**Comment by marziman** [comment]
Ok I will take a look and check this.
Thanks for pointing it out and sorry if this happened.

**Comment by Landstad** [comment]
Hello @digitaldan  @marziman,

I see this issue was closed four days ago, but I am still experiencing the same behavior.

**Comment by Landstad** [comment]
@digitaldan when will the fix be deployed?

**Comment by cweitkamp** [comment]
I submitted a follow-up PR to solve the issue for the buttons "Prev" and "Next".
